import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY")!;
const CF_ACCOUNT_ID = Deno.env.get("CF_ACCOUNT_ID")!;
const CF_KV_NAMESPACE_ID = Deno.env.get("CF_KV_NAMESPACE_ID")!;
const CF_API_TOKEN = Deno.env.get("CF_API_TOKEN")!;
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const APPS_BASE_URL = Deno.env.get("APPS_BASE_URL") || "https://apps.cottix.co";

const MAX_GENERATIONS_PER_DAY = 20;

// ---------- SYSTEM PROMPT ----------

const SYSTEM_PROMPT = `You are an expert mobile app developer. You create single-file HTML apps that run perfectly on mobile phones.

CONSTRAINTS — follow ALL of these strictly:
1. Output ONLY a single HTML file. No explanations, no markdown fences, no commentary. Just the raw HTML starting with <!DOCTYPE html>.
2. ALL CSS must be inline in a <style> tag. ALL JavaScript must be inline in a <script> tag. NO external resources, NO CDN links, NO imports.
3. Include <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover"> in the <head>.
4. Mobile-first design: touch targets minimum 44px, font-size minimum 16px for inputs (prevents iOS zoom), no hover-dependent interactions.
5. Visual style: clean, modern, iOS-native feel. Use -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif font stack. White or light background. Primary accent #007AFF (iOS blue). Rounded corners (12px for cards, 8px for buttons). Subtle shadows for depth.
6. Use localStorage for ALL data persistence. Key naming: use a descriptive prefix related to the app purpose (e.g., "tambola_", "tracker_", "todo_").
7. The app must be FULLY FUNCTIONAL — not a mockup. All buttons must work, all data must save and load, all features must be implemented.
8. Include a <title> tag with a short descriptive app name.
9. Include this meta tag for Cottix metadata extraction:
   <meta name="cottix-meta" content='{"icon":"EMOJI","color":"HEX_COLOR","description":"SHORT_DESCRIPTION"}'>
   Choose an appropriate emoji icon and soft pastel background color (#DBEAFE blue, #D1FAE5 green, #FEF3C7 yellow, #FCE7F3 pink, #E0E7FF indigo, #FEE2E2 red, #F3E8FF purple, #E5E7EB gray).
10. Handle empty states gracefully — show helpful placeholder text when no data exists yet.
11. Add subtle feedback: button press animations (scale 0.96 on active), smooth transitions (transition: all 0.15s ease).
12. If the app involves multiple people or sharing, design it so each person can use it on their own phone by opening the same URL. Use localStorage per-device.
13. Support safe-area-insets: padding-top: env(safe-area-inset-top); padding-bottom: max(env(safe-area-inset-bottom), 16px).
14. NEVER include any comments like "<!-- Generated by..." in the output.

OUTPUT: Raw HTML only. Nothing else.`;

// ---------- HELPERS ----------

function generateAppId(): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  let id = "";
  for (let i = 0; i < 8; i++) {
    id += chars[Math.floor(Math.random() * chars.length)];
  }
  return id;
}

function extractMetadata(html: string): {
  title: string;
  icon: string;
  color: string;
  description: string;
} {
  const titleMatch = html.match(/<title>(.*?)<\/title>/i);
  const title = titleMatch?.[1] || "My App";

  // Support both cottix-meta and legacy perappos-meta tags
  const metaMatch = html.match(
    /<meta\s+name="(?:cottix|perappos)-meta"\s+content='({.*?})'/i
  );
  let icon = "✨";
  let color = "#E0E7FF";
  let description = "";

  if (metaMatch) {
    try {
      const meta = JSON.parse(metaMatch[1]);
      icon = meta.icon || icon;
      color = meta.color || color;
      description = meta.description || description;
    } catch {
      // ignore parse errors
    }
  }

  return { title, icon, color, description };
}

async function publishToCloudflare(appId: string, html: string): Promise<string> {
  const url = `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/storage/kv/namespaces/${CF_KV_NAMESPACE_ID}/values/app:${appId}`;

  const resp = await fetch(url, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${CF_API_TOKEN}`,
      "Content-Type": "text/plain",
    },
    body: html,
  });

  if (!resp.ok) {
    const error = await resp.text();
    throw new Error(`Cloudflare KV write failed: ${resp.status} ${error}`);
  }

  return `${APPS_BASE_URL}/${appId}`;
}

// Stream Claude's response, calling onChunk for each text delta.
// Returns the full HTML string.
async function callClaudeStream(
  messages: Array<{ role: string; content: string }>,
  onChunk: (text: string, totalChars: number) => Promise<void>
): Promise<string> {
  const resp = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 8192,
      stream: true,
      system: SYSTEM_PROMPT,
      messages,
    }),
  });

  if (!resp.ok) {
    const error = await resp.text();
    throw new Error(`Anthropic API error: ${resp.status} ${error}`);
  }

  let fullText = "";
  let totalChars = 0;
  let lastProgressAt = 0;
  const reader = resp.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";

    for (const line of lines) {
      if (!line.startsWith("data: ")) continue;
      const raw = line.slice(6).trim();
      if (raw === "[DONE]") continue;
      try {
        const event = JSON.parse(raw);
        if (
          event.type === "content_block_delta" &&
          event.delta?.type === "text_delta"
        ) {
          const text: string = event.delta.text;
          fullText += text;
          totalChars += text.length;
          // Send a progress event every ~200 chars
          if (totalChars - lastProgressAt >= 200) {
            lastProgressAt = totalChars;
            await onChunk(text, totalChars);
          }
        }
      } catch {
        // ignore SSE parse errors
      }
    }
  }

  // Strip markdown fences if Claude wrapped the output
  return fullText
    .replace(/^```html?\n?/i, "")
    .replace(/\n?```$/i, "")
    .trim();
}

// ---------- HANDLER ----------

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey",
      },
    });
  }

  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Missing auth" }), {
        status: 401,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Strip "Bearer " or "bearer " prefix (case-insensitive)
    const token = authHeader.replace(/^bearer\s+/i, "");

    // Decode JWT locally — Supabase infrastructure already validates the signature.
    // This avoids a round-trip to the auth service which has been unreliable in edge functions.
    let userId: string;
    try {
      const parts = token.split(".");
      if (parts.length !== 3) throw new Error("malformed JWT");
      // JWT uses base64url (no padding); atob() requires standard base64 with padding
      const seg = parts[1].replace(/-/g, "+").replace(/_/g, "/");
      const padded = seg + "=".repeat((4 - (seg.length % 4)) % 4);
      const payload = JSON.parse(atob(padded));
      // Supabase user JWTs use `aud: "authenticated"` (not `role`)
      // Service-role API keys use `role: "service_role"`
      const isAuthenticated =
        payload.aud === "authenticated" || payload.role === "authenticated";
      console.log("JWT aud:", payload.aud, "role:", payload.role, "sub:", payload.sub);
      if (!isAuthenticated || !payload.sub) {
        throw new Error(`not authenticated (aud=${payload.aud}, role=${payload.role})`);
      }
      if (payload.exp < Math.floor(Date.now() / 1000)) {
        throw new Error("token expired");
      }
      userId = payload.sub as string;
    } catch (err) {
      console.error("JWT decode error:", err instanceof Error ? err.message : err);
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Use service role client for all database operations
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Rate limiting
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const { count } = await supabase
      .from("generated_apps")
      .select("*", { count: "exact", head: true })
      .eq("user_id", userId)
      .gte("created_at", today.toISOString());

    if ((count ?? 0) >= MAX_GENERATIONS_PER_DAY) {
      return new Response(
        JSON.stringify({
          error: "Daily generation limit reached",
          limit: MAX_GENERATIONS_PER_DAY,
        }),
        { status: 429, headers: { "Content-Type": "application/json" } }
      );
    }

    const body = await req.json();
    const { prompt, appId: existingAppId, conversationHistory } = body;

    if (!prompt || typeof prompt !== "string" || prompt.trim().length === 0) {
      return new Response(JSON.stringify({ error: "Prompt is required" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    let messages: Array<{ role: string; content: string }>;
    if (conversationHistory && Array.isArray(conversationHistory)) {
      messages = [...conversationHistory, { role: "user", content: prompt }];
    } else {
      messages = [{ role: "user", content: prompt }];
    }

    // ---------- SSE streaming response ----------
    const { readable, writable } = new TransformStream<Uint8Array, Uint8Array>();
    const writer = writable.getWriter();
    const enc = new TextEncoder();

    const writeSSE = async (event: string, data: unknown) => {
      await writer.write(
        enc.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)
      );
    };

    // Run generation in background so we can return the stream immediately
    (async () => {
      try {
        const html = await callClaudeStream(
          messages,
          async (_chunk, totalChars) => {
            await writeSSE("progress", { chars: totalChars });
          }
        );

        if (!html.includes("<!DOCTYPE") && !html.includes("<html")) {
          await writeSSE("error", {
            message: "Generation failed — did not produce valid HTML. Try again.",
          });
          return;
        }

        const metadata = extractMetadata(html);
        const appId = existingAppId || generateAppId();
        const hostedUrl = await publishToCloudflare(appId, html);

        const updatedHistory = [
          ...messages,
          { role: "assistant", content: html },
        ];
        const htmlSize = new TextEncoder().encode(html).length;

        if (existingAppId) {
          await supabase
            .from("generated_apps")
            .update({
              conversation_history: updatedHistory,
              html_size: htmlSize,
              title: metadata.title,
              description: metadata.description,
              icon_emoji: metadata.icon,
              icon_bg_color: metadata.color,
              updated_at: new Date().toISOString(),
            })
            .eq("app_id", existingAppId)
            .eq("user_id", userId);
        } else {
          await supabase.from("generated_apps").insert({
            user_id: userId,
            app_id: appId,
            prompt: prompt,
            title: metadata.title,
            description: metadata.description,
            icon_emoji: metadata.icon,
            icon_bg_color: metadata.color,
            html_size: htmlSize,
            hosted_url: hostedUrl,
            conversation_history: updatedHistory,
          });
        }

        await writeSSE("done", {
          url: hostedUrl,
          appId,
          title: metadata.title,
          description: metadata.description,
          icon: metadata.icon,
          color: metadata.color,
          htmlSize,
        });
      } catch (err) {
        console.error("generate-app stream error:", err);
        await writeSSE("error", {
          message: err instanceof Error ? err.message : "Internal error",
        });
      } finally {
        await writer.close();
      }
    })();

    return new Response(readable, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey",
      },
    });
  } catch (err) {
    console.error("generate-app error:", err);
    return new Response(
      JSON.stringify({
        error: err instanceof Error ? err.message : "Internal error",
      }),
      {
        status: 500,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      }
    );
  }
});
